// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Backendify.Api.Repositories
{
    [DbContext(typeof(CompanyRepository))]
    public partial class CompanyRepositoryModel : RuntimeModel
    {
        static CompanyRepositoryModel()
        {
            var model = new CompanyRepositoryModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static CompanyRepositoryModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
